---
- name: test if vdo_devices is set correctly
  assert:
    that:
      - vdo_devices is iterable
    quiet: yes
  when:
    - vdo_devices is defined

- name: test if item in vdo_devices is set correctly
  assert:
    that:
      - item.name is defined
      - item.device is defined
      - item.logicalsize is defined
    quiet: yes
  loop: "{{ vdo_devices }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - vdo_devices is defined
