---
# tasks file for vdo

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Install requirements
  ansible.builtin.package:
    name: "{{ vdo_packages }}"
    state: present

- name: Start and enable service
  ansible.builtin.service:
    name: "{{ vdo_service }}"
    state: started
    enabled: yes

- name: Create vdo device
  community.general.vdo:
    name: "{{ item.name }}"
    state: present
    device: "{{ item.device }}"
    logicalsize: "{{ item.logicalsize }}"
  loop: "{{ vdo_devices }}"
  when:
    - vdo_devices is defined
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
